---
title: "Introduction and Dataset Description"
author: "Becky Catlett"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The dataset we are exploring in this project is from Kaggle and is called "Top Spotify Tracks of 2018." This dataset includes numerous quantitative variables as well as some qualitative variables, such as the song title, artist, and the Spotify url ID. The quantitative variables are slightly less intuitive, such as danceability, energy, key, loudness (in dB), mode, speechiness, and acousticness. Most of these quantitative variables range from 0 to 1, where 1 is the highest measure and 0 indicates a low/null value. Danceability describes how suitable a track is for dancing based on a combination of musical elements including tempo, rhythm stability, beat strength, and overall regularity. Speechiness is how often words are present in the song, and mode indicates the modality, which is whether the song is written in major (1) or minor (0). Acousticness is how acoustic the song is, versus a non-acoustic song which would be composed of lots of electronics. Energy is essentially describing the tempo of the song, whether is song is slower and sleepier or more upbeat. **INCLUDE THIS IF DOING PCA ->** Thinking about these variables, it makes sense that there could be some correlation between variables, like how energy could be correlated with danceability and loudness.

We will be using PCA and clustering analysis to find an model structure of the data that is more easily interpreted. The goal of this is to gain an understanding of music popularity in 2018 using Spotify data. We will be using PCA to reduce the number of dimensions since there are so many correlated variables in the data set **PROVE THIS OR WE DONT USE PCA**. From here, we will explore k-means, hierarchical, and model-based clustering to analyze the data and see what relationships occur between variables that may not be obvious without the application of clustering methods.

**BELOW IS AN IDEA FOR THIS BULLET IN THE PROJECT DESCRIPTION**
**Model section that discusses the specific methodology and statistical approach you are using the analyze the data**
Below is code for three different clustering techniques, from which we will chose one to use for our analysis of the Spotify data. Including all three methods ensures that the method we choose for our anaysis is one that best minimizes the **variance?** of the data. Although all statistical results have uncertainty, the goal is to use the best statistical method to get rid of a lot of uncertainty in the results. Clustering/classification results are useful for artists, songwriters, producers, and many more individuals that are looking for qualities of a hit song.



